apiVersion: v1
kind: Namespace
metadata:
  name: resource-quota-example
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota-name
  namespace: resource-quota-example
spec:
  hard:
    requests.cpu: '500m'
    requests.memory: 500Mi
    limits.cpu: '1'
    limits.memory: 1Gi
    pods: '2'
    persistentvolumeclaims: '2'
    requests.storage: 5Gi